FROM quay.io/centos/centos:stream8

RUN sed -i "s/enabled=0/enabled=1/" /etc/yum.repos.d/CentOS-Stream-PowerTools.repo && \
    dnf -y install gcc python38-devel xmlsec1-devel xmlsec1-openssl-devel libtool-ltdl-devel && \
    dnf -y update

ENV PATH /venv/bin:${PATH} \
    VIRTUAL_ENV /venv

RUN python3 -m venv /venv
RUN pip3 install --no-cache-dir --upgrade pip wheel
RUN pip3 wheel --no-deps --wheel-dir /dist xmlsec
